# Generated by Django 3.1.12 on 2025-04-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_stockavailability_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='list',
        ),
    ]
