# Generated by Django 3.1.12 on 2025-04-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_remove_groceryitem_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistitems',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grocery.grocerylist'),
        ),
    ]
