# Generated by Django 3.1.12 on 2025-04-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_auto_20250416_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistitems',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.grocerylist'),
        ),
    ]
