# Generated by Django 5.2 on 2025-04-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_pantrymanagement_delete_task_groceryitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='product',
        ),
    ]
