# Generated by Django 5.2 on 2025-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_alter_category_options_alter_groceryitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Grains', 'Grains'), ('Beverages', 'Beverages'), ('Sweets', 'Sweets'), ('Snacks', 'Snacks'), ('Condiments', 'Condiments'), ('Bakery', 'Bakery')], max_length=50, null=True),
        ),
    ]
